
const constants = {

  INCREMENT_STEP: 'INCREMENT_STEP',
  DECREMENT_STEP: 'DECREMENT_STEP',
  CLICK_REPORT_TYPE: 'CLICK_REPORT_TYPE',
  CLICK_ADDRESS_LOOKUP: 'CLICK_ADDRESS_LOOKUP',
  REQUEST_SITES_BY_PHONE: 'REQUEST_SITES_BY_PHONE',
  RECEIVE_SITES_BY_PHONE: 'RECEIVE_SITES_BY_PHONE',
  REQUEST_SITES_BY_ADDRESS: 'REQUEST_SITES_BY_ADDRESS',
  RECEIVE_SITES_BY_ADDRESS: 'RECEIVE_SITES_BY_ADDRESS',
  SELECT_LOOKUP: 'SELECT_LOOKUP',
  OUTAGE_TYPE: 'OUTAGE_TYPE',
  QUESTIONARIE_STEP1: 'QUESTIONARIE_STEP1',
  SERVER_ERROR: 'SERVER_ERROR',

}

export default constants
