
const constants = {

  INCREMENT_STEP: 'INCREMENT_STEP',
  DECREMENT_STEP: 'DECREMENT_STEP',
  CLICK_REPORT_TYPE: 'CLICK_REPORT_TYPE',
  CLICK_ADDRESS_LOOKUP: 'CLICK_ADDRESS_LOOKUP',
  REQUEST_SITES_BY_PHONE: 'REQUEST_SITES_BY_PHONE',
  RECEIVE_SITES_BY_PHONE: 'RECEIVE_SITES_BY_PHONE',
  REQUEST_SITES_BY_ADDRESS: 'REQUEST_SITES_BY_ADDRESS',
  RECEIVE_SITES_BY_ADDRESS: 'RECEIVE_SITES_BY_ADDRESS',
  SELECT_LOOKUP: 'SELECT_LOOKUP',
  OUTAGE_TYPE: 'OUTAGE_TYPE',
  QUESTIONARIE_STEP1: 'QUESTIONARIE_STEP1',
  SERVER_ERROR: 'SERVER_ERROR',
  SELECT_STATUS_LOOKUP:"SELECT_STATUS_LOOKUP",
  RESET_STATE:"RESET_STATE",
  CONTACT_INFO:"CONTACT_INFO",
  OUTAGETYPE_SUBMIT:"OUTAGETYPE_SUBMIT",
  PARSE_ADDRESS:"PARSE_ADDRESS",
  RECEIVE_ADDRESS_ERROR:"RECEIVE_ADDRESS_ERROR",
  OUTAGETYPE_CHANGED:"OUTAGETYPE_CHANGED",
  SUBMIT_OUTAGE:"SUBMIT_OUTAGE",
  DUPLICATE_OUTAGE:"DUPLICATE_OUTAGE",
  DNP_FLAG:"DNP_FLAG"
}

export default constants
